### ISSUE TITLE
How to train SE-WResNetV2?

### ISSUE THREAD

**Issue by lbin** [ansleliu/LightNet#8]
I got some errors like:

> RuntimeError: cuda runtime error (2) : out of memory 

How to solve this problem?

Thanks

**Comment by ansleliu** [comment]
@ @lbin Hi, please make sure that you use at least one GPU with more than 11G memory, and select a suitable batch size for training. ^_^

**Comment by lbin** [comment]
Thank you very much for your suggestion. I will try it later. 
By the way, Could  you share your SE-WResNetV2 pre-trained model on ImageNet?

**Comment by Paranoidv** [comment]
@ansleliu 
Haha, I have the same ask with @lbin Could you share your SE-WResNetV2 pre-trained model on ImageNet? Tahnk you, I have got the wide-resenet38 model from Inplace_abn, but it is not the model that i need , so , if you kindly share the SE-WResNetV2 pre-trained model, very appericate it, because I have't enough GPU to train model with ImageNet dataset!!!!!!!!!!!!!!!Thank you !!!!

**Comment by ansleliu** [comment]
@lbin @Paranoidv 
You can try to use [this one](https://drive.google.com/open?id=1BpwQJzl9dLR7kb71dM1ZsZQOwtLOZF-6) to train with cityscapes or mapillary dataset, it was modified from official repo of [inplace_abn](https://github.com/mapillary/inplace_abn). ^_^

**Comment by lbin** [comment]
@ansleliu Thanks, I will try later~

**Comment by Paranoidv** [comment]
@ansleliu 
Thanks for your reply, I will try it, Beacause I have not enough powerful GPU to pre_train wide_resnet with ImageNet dataset, so,  I think maybe you could share with me. Thank you!!!!!1
